// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_gridlock_breaker = "CgkIjMX6284JEAIQDQ"; // <GPGSID>
        public const string achievement_untouched_grandmaster = "CgkIjMX6284JEAIQDA"; // <GPGSID>
        public const string achievement_rapid_fire_solver = "CgkIjMX6284JEAIQEA"; // <GPGSID>
        public const string achievement_grid_grasper = "CgkIjMX6284JEAIQAw"; // <GPGSID>
        public const string achievement_master_mover = "CgkIjMX6284JEAIQBg"; // <GPGSID>
        public const string achievement_pattern_pro = "CgkIjMX6284JEAIQBA"; // <GPGSID>
        public const string achievement_lightning_quick = "CgkIjMX6284JEAIQBw"; // <GPGSID>
        public const string achievement_first_solve = "CgkIjMX6284JEAIQAA"; // <GPGSID>
        public const string achievement_grand_prix_finisher = "CgkIjMX6284JEAIQCQ"; // <GPGSID>
        public const string achievement_puzzle_apprentice = "CgkIjMX6284JEAIQAg"; // <GPGSID>
        public const string achievement_efficiency_master = "CgkIjMX6284JEAIQCw"; // <GPGSID>
        public const string achievement_the_unstoppable = "CgkIjMX6284JEAIQDg"; // <GPGSID>
        public const string achievement_logic_luminary = "CgkIjMX6284JEAIQBQ"; // <GPGSID>
        public const string achievement_flawless_sprint = "CgkIjMX6284JEAIQCA"; // <GPGSID>
        public const string achievement_minimalist_mover = "CgkIjMX6284JEAIQDw"; // <GPGSID>
        public const string achievement_epic_journey = "CgkIjMX6284JEAIQEQ"; // <GPGSID>
        public const string achievement_speed_demon = "CgkIjMX6284JEAIQCg"; // <GPGSID>

}

